---
title: "PA 446 Midterm Part I"
author: "Leah Berti"
date: "2025-10-16"
output: 
  html_document:
    theme: cerulean
editor_options: 
  chunk_output_type: console
---

```{r}
# loading library
library(usethis)

# configuration
use_git_config(user.name = "Leah Berti", user.email = "lsberti@yahoo.com")

# initiating repository
use_git()
```

Food waste is a problem that is both environmental and economic in nature. 
Industrial levels of agricultural production have been a boon to ensuring 
relatively high and consistent supplies of food in much of the world, yet mis-
matches between supply and demand related to pricing, geopolitical conditions, 
and other issues lead to situations where resource-intensive processes involved 
in producing a robust food supply are conducted in vain. 

By wasting food, society wastes opportunities to ensure that hungry people are 
fed (in cases of edible food waste) and to harness the potential of composted 
food to nourish soil and produce biofuel (in the case of food scraps). Further-
more, money spent on uneaten food is still a charge passed on to customers at
grocery stores and restaurants, so less money spent on wasted food should 
translate to lower prices passed on to customers.

Market incentives like tax credits and subsidies for producers to generate 
supplies that match demand, implementing public messaging campaigns, and 
providing a mechanism for surplus food to be matched with people who can least 
afford it, units of government can meaningfully combat food waste. Tax credits 
could be offered to businesses that compost and donate high-quality leftovers 
that would otherwise go to waste. Subsidies could be offered to businesses and
organizations that want to compost and donate food, but need help getting start-
ed. Public awareness campaigns could be used to promote household and commercial
composting on social media and more through more "old school" advertising 
channels like television, print news, and billboards. 

